// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dotnet_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230829163919_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Desk", b =>
                {
                    b.Property<string>("DeskName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BookingEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BookingStartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("DeskName");

                    b.HasIndex("LocationName");

                    b.ToTable("Desks");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Property<string>("LocationName")
                        .HasColumnType("TEXT");

                    b.HasKey("LocationName");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Desk", b =>
                {
                    b.HasOne("Location", null)
                        .WithMany("Desks")
                        .HasForeignKey("LocationName");
                });

            modelBuilder.Entity("Location", b =>
                {
                    b.Navigation("Desks");
                });
#pragma warning restore 612, 618
        }
    }
}
