name: Build and Test Angular and .NET Core Applications with Docker Compose

on:
  push:
    branches:
      - main
      - feature/cicd

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19.1"

      - name: Install Angular dependencies
        run: |
          npm install -g @angular/cli
          cd AngularApp
          npm install

      - name: Build Angular App
        run: |
          cd AngularApp
          ng build --prod

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Start SQL Server via Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Build and Test .NET Web API
        run: |
          cd WebApi
          dotnet build
          dotnet test --filter "Category!=Integration"

      - name: Run Integration Tests
        run: |
          cd WebApi.IntegrationTests
          dotnet test --filter "Category=Integration"

      - name: Stop Docker Compose services
        run: |
          docker-compose -f docker-compose.yml down
